### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [diwash007/PDF-Dark-Mode#3]
Hey @diwash007 assign me this issue under **hactoberfest**
I will add guidelines to this repo!

**Comment by diwash007** [comment]
sure, go ahead

**Comment by gurjeetsinghvirdee** [comment]
can you assign me!

**Comment by anamikarawat** [comment]
Hey @diwash007 assign me this issue under hactoberfest 2022
I will add guidelines to this repo!
